apiVersion: v1
kind: Namespace
metadata:
  name: hibana
  labels:
    app.kubernetes.io/part-of: hibana
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.35
