apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hibana
resources:
  - ../base
  - ../console
  - ingress.yaml
patches:
  - target:
      kind: ConfigMap
      name: hibana-config
    patch: |-
      - op: replace
        path: /data/TRUSTED_PROXY_CIDRS
        value: CHANGE_ME_TRUSTED_PROXY_CIDRS
