//! Frozen constraints and indexes for m20260915_000001_platform.
use sea_orm_migration::prelude::*;
pub async fn create(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    manager
        .create_index(
            Index::create()
                .name("api_tokens_token_hash_key")
                .table("api_tokens")
                .unique()
                .col("token_hash")
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("component_versions_component_id_version_key")
                .table("component_versions")
                .unique()
                .col("component_id")
                .col("version")
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("component_versions_tenant_component_id_key")
                .table("component_versions")
                .unique()
                .col("tenant_id")
                .col("component_id")
                .col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("components_tenant_id_id_key")
                .table("components")
                .unique()
                .col("tenant_id")
                .col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("function_secrets_tenant_component_id_name_key")
                .table("function_secrets")
                .unique()
                .col("tenant_id")
                .col("component_id")
                .col("id")
                .col("name")
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("function_secrets_tenant_id_id_key")
                .table("function_secrets")
                .unique()
                .col("tenant_id")
                .col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("tenants_slug_key")
                .table("tenants")
                .unique()
                .col("slug")
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("users_tenant_id_email_key")
                .table("users")
                .unique()
                .col("tenant_id")
                .col("email")
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("users_tenant_id_id_key")
                .table("users")
                .unique()
                .col("tenant_id")
                .col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("api_tokens_tenant_id_fkey")
                .from_tbl("api_tokens")
                .from_col("tenant_id")
                .to_tbl("tenants")
                .to_col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("artifact_reservations_tenant_id_fkey")
                .from_tbl("artifact_reservations")
                .from_col("tenant_id")
                .to_tbl("tenants")
                .to_col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("audit_logs_tenant_id_fkey")
                .from_tbl("audit_logs")
                .from_col("tenant_id")
                .to_tbl("tenants")
                .to_col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("component_signing_keys_tenant_id_fkey")
                .from_tbl("component_signing_keys")
                .from_col("tenant_id")
                .to_tbl("tenants")
                .to_col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("component_versions_tenant_id_fkey")
                .from_tbl("component_versions")
                .from_col("tenant_id")
                .to_tbl("tenants")
                .to_col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("components_tenant_id_fkey")
                .from_tbl("components")
                .from_col("tenant_id")
                .to_tbl("tenants")
                .to_col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("executions_tenant_id_fkey")
                .from_tbl("executions")
                .from_col("tenant_id")
                .to_tbl("tenants")
                .to_col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("function_secret_versions_tenant_id_fkey")
                .from_tbl("function_secret_versions")
                .from_col("tenant_id")
                .to_tbl("tenants")
                .to_col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("function_secret_versions_tenant_id_secret_id_fkey")
                .from_tbl("function_secret_versions")
                .from_col("tenant_id")
                .from_col("secret_id")
                .to_tbl("function_secrets")
                .to_col("tenant_id")
                .to_col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("function_secrets_tenant_id_component_id_fkey")
                .from_tbl("function_secrets")
                .from_col("tenant_id")
                .from_col("component_id")
                .to_tbl("components")
                .to_col("tenant_id")
                .to_col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("function_secrets_tenant_id_fkey")
                .from_tbl("function_secrets")
                .from_col("tenant_id")
                .to_tbl("tenants")
                .to_col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("usage_rollups_tenant_id_fkey")
                .from_tbl("usage_rollups")
                .from_col("tenant_id")
                .to_tbl("tenants")
                .to_col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("users_tenant_id_fkey")
                .from_tbl("users")
                .from_col("tenant_id")
                .to_tbl("tenants")
                .to_col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("version_configs_tenant_id_component_id_version_id_fkey")
                .from_tbl("version_configs")
                .from_col("tenant_id")
                .from_col("component_id")
                .from_col("version_id")
                .to_tbl("component_versions")
                .to_col("tenant_id")
                .to_col("component_id")
                .to_col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("version_secret_bindings_tenant_id_component_id_secret_id_n_fkey")
                .from_tbl("version_secret_bindings")
                .from_col("tenant_id")
                .from_col("component_id")
                .from_col("secret_id")
                .from_col("name")
                .to_tbl("function_secrets")
                .to_col("tenant_id")
                .to_col("component_id")
                .to_col("id")
                .to_col("name")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("version_secret_bindings_tenant_id_component_id_version_id_fkey")
                .from_tbl("version_secret_bindings")
                .from_col("tenant_id")
                .from_col("component_id")
                .from_col("version_id")
                .to_tbl("component_versions")
                .to_col("tenant_id")
                .to_col("component_id")
                .to_col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("api_tokens_user_tenant_fkey")
                .from_tbl("api_tokens")
                .from_col("tenant_id")
                .from_col("user_id")
                .to_tbl("users")
                .to_col("tenant_id")
                .to_col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("component_versions_component_tenant_fkey")
                .from_tbl("component_versions")
                .from_col("tenant_id")
                .from_col("component_id")
                .to_tbl("components")
                .to_col("tenant_id")
                .to_col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("executions_version_tenant_fkey")
                .from_tbl("executions")
                .from_col("tenant_id")
                .from_col("component_id")
                .from_col("version_id")
                .to_tbl("component_versions")
                .to_col("tenant_id")
                .to_col("component_id")
                .to_col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("usage_rollups_component_tenant_fkey")
                .from_tbl("usage_rollups")
                .from_col("tenant_id")
                .from_col("component_id")
                .to_tbl("components")
                .to_col("tenant_id")
                .to_col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("components_active_version_fkey")
                .from_tbl("components")
                .from_col("tenant_id")
                .from_col("id")
                .from_col("active_version_id")
                .to_tbl("component_versions")
                .to_col("tenant_id")
                .to_col("component_id")
                .to_col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_foreign_key(
            ForeignKey::create()
                .name("components_previous_version_fkey")
                .from_tbl("components")
                .from_col("tenant_id")
                .from_col("id")
                .from_col("previous_active_version_id")
                .to_tbl("component_versions")
                .to_col("tenant_id")
                .to_col("component_id")
                .to_col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("artifact_reservations_cleanup")
                .table("artifact_reservations")
                .col("tenant_id")
                .col("cleanup_retry_at")
                .col("expires_at")
                .col("id")
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("artifact_reservations_expiry")
                .table("artifact_reservations")
                .col("tenant_id")
                .col("expires_at")
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("components_live_tenant_name")
                .table("components")
                .unique()
                .col("tenant_id")
                .col("name")
                .and_where(Expr::cust("(deleted_at IS NULL)"))
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("idx_api_tokens_tenant")
                .table("api_tokens")
                .col("tenant_id")
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("idx_audit_logs_tenant_created")
                .table("audit_logs")
                .col("tenant_id")
                .col(("created_at", IndexOrder::Desc))
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("idx_component_versions_component")
                .table("component_versions")
                .col("component_id")
                .col(("created_at", IndexOrder::Desc))
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("idx_executions_component_finished")
                .table("executions")
                .col("tenant_id")
                .col("component_id")
                .col(("finished_at", IndexOrder::Desc))
                .and_where(Expr::cust(
                    "(status = ANY (ARRAY['succeeded'::text, 'failed'::text, 'timeout'::text]))",
                ))
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("idx_executions_component_status")
                .table("executions")
                .col("component_id")
                .col("status")
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("idx_executions_http_inflight")
                .table("executions")
                .col("tenant_id")
                .col("created_at")
                .and_where(Expr::cust(
                    "(http_request AND (status = ANY (ARRAY['pending'::text, 'running'::text])))",
                ))
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("idx_executions_tenant_created")
                .table("executions")
                .col("tenant_id")
                .col(("created_at", IndexOrder::Desc))
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("idx_executions_tenant_finished")
                .table("executions")
                .col("tenant_id")
                .col(("finished_at", IndexOrder::Desc))
                .and_where(Expr::cust(
                    "(status = ANY (ARRAY['succeeded'::text, 'failed'::text, 'timeout'::text]))",
                ))
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("idx_function_secret_versions_created")
                .table("function_secret_versions")
                .col("tenant_id")
                .col("secret_id")
                .col(("created_at", IndexOrder::Desc))
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("idx_function_secrets_component")
                .table("function_secrets")
                .col("tenant_id")
                .col("component_id")
                .and_where(Expr::cust("(deleted_at IS NULL)"))
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("idx_usage_rollups_tenant_period")
                .table("usage_rollups")
                .col("tenant_id")
                .col(("period_start", IndexOrder::Desc))
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("uq_function_secrets_live_name")
                .table("function_secrets")
                .unique()
                .col("tenant_id")
                .col("component_id")
                .col("name")
                .and_where(Expr::cust("(deleted_at IS NULL)"))
                .to_owned(),
        )
        .await?;
    Ok(())
}
