use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // Frozen baseline: future model edits require a new migration file.
        super::assert_empty_schema(manager).await?;
        manager
            .create_table(
                Table::create()
                    .table("tenants")
                    .check(Expr::col("status").is_in(["active", "suspended"]))
                    .col(ColumnDef::new("id").text().not_null().primary_key())
                    .col(ColumnDef::new("slug").text().not_null())
                    .col(ColumnDef::new("name").text().not_null())
                    .col(
                        ColumnDef::new("status")
                            .text()
                            .not_null()
                            .default(Expr::cust("'active'::text")),
                    )
                    .col(
                        ColumnDef::new("created_at")
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .col(
                        ColumnDef::new("quotas")
                            .json_binary()
                            .not_null()
                            .default(Expr::cust("'{}'::jsonb")),
                    )
                    .col(
                        ColumnDef::new("require_signed_components")
                            .boolean()
                            .not_null()
                            .default(Expr::cust("false")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table("users")
                    .check(Expr::col("role").is_in(["member", "admin"]))
                    .col(ColumnDef::new("id").text().not_null().primary_key())
                    .col(ColumnDef::new("tenant_id").text().not_null())
                    .col(ColumnDef::new("email").text().not_null())
                    .col(ColumnDef::new("password_hash").text().not_null())
                    .col(ColumnDef::new("role").text().not_null())
                    .col(
                        ColumnDef::new("created_at")
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .col(ColumnDef::new("deleted_at").timestamp_with_time_zone())
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table("api_tokens")
                    .check(Expr::cust(
                        "scopes <@ ARRAY['read', 'invoke', 'deploy', 'admin']::text[]",
                    ))
                    .col(ColumnDef::new("id").text().not_null().primary_key())
                    .col(ColumnDef::new("tenant_id").text().not_null())
                    .col(ColumnDef::new("user_id").text())
                    .col(ColumnDef::new("token_hash").text().not_null())
                    .col(ColumnDef::new("scopes").array(ColumnType::Text).not_null())
                    .col(ColumnDef::new("name").text())
                    .col(
                        ColumnDef::new("created_at")
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .col(
                        ColumnDef::new("expires_at")
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(ColumnDef::new("revoked_at").timestamp_with_time_zone())
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table("audit_logs")
                    .col(
                        ColumnDef::new("id")
                            .big_integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new("tenant_id").text().not_null())
                    .col(ColumnDef::new("actor").text())
                    .col(ColumnDef::new("action").text().not_null())
                    .col(ColumnDef::new("target").text())
                    .col(ColumnDef::new("detail").json_binary())
                    .col(
                        ColumnDef::new("created_at")
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table("components")
                    .col(ColumnDef::new("id").text().not_null().primary_key())
                    .col(ColumnDef::new("tenant_id").text().not_null())
                    .col(ColumnDef::new("name").text().not_null())
                    .col(ColumnDef::new("active_version_id").text())
                    .col(
                        ColumnDef::new("created_at")
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .col(ColumnDef::new("deleted_at").timestamp_with_time_zone())
                    .col(ColumnDef::new("previous_active_version_id").text())
                    .col(
                        ColumnDef::new("ingress_enabled")
                            .boolean()
                            .not_null()
                            .default(Expr::cust("false")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table("component_versions")
                    .check(Expr::col("status").is_in(["pending", "active", "deprecated"]))
                    .col(ColumnDef::new("id").text().not_null().primary_key())
                    .col(ColumnDef::new("component_id").text().not_null())
                    .col(ColumnDef::new("tenant_id").text().not_null())
                    .col(ColumnDef::new("version").text().not_null())
                    .col(ColumnDef::new("storage_uri").text().not_null())
                    .col(ColumnDef::new("wasm_sha256").text().not_null())
                    .col(
                        ColumnDef::new("resource_limits")
                            .json_binary()
                            .not_null()
                            .default(Expr::cust("'{}'::jsonb")),
                    )
                    .col(
                        ColumnDef::new("status")
                            .text()
                            .not_null()
                            .default(Expr::cust("'pending'::text")),
                    )
                    .col(
                        ColumnDef::new("created_at")
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .col(
                        ColumnDef::new("size_bytes")
                            .big_integer()
                            .not_null()
                            .default(Expr::cust("0")),
                    )
                    .col(
                        ColumnDef::new("capabilities")
                            .json_binary()
                            .not_null()
                            .default(Expr::cust("'[]'::jsonb")),
                    )
                    .col(ColumnDef::new("deleted_at").timestamp_with_time_zone())
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table("executions")
                    .check(Expr::col("status").is_in([
                        "pending",
                        "running",
                        "succeeded",
                        "failed",
                        "timeout",
                    ]))
                    .col(ColumnDef::new("id").text().not_null().primary_key())
                    .col(ColumnDef::new("tenant_id").text().not_null())
                    .col(ColumnDef::new("component_id").text().not_null())
                    .col(ColumnDef::new("version_id").text().not_null())
                    .col(
                        ColumnDef::new("status")
                            .text()
                            .not_null()
                            .default(Expr::cust("'pending'::text")),
                    )
                    .col(ColumnDef::new("input").json_binary())
                    .col(ColumnDef::new("output").json_binary())
                    .col(ColumnDef::new("error").json_binary())
                    .col(
                        ColumnDef::new("created_at")
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .col(ColumnDef::new("started_at").timestamp_with_time_zone())
                    .col(ColumnDef::new("finished_at").timestamp_with_time_zone())
                    .col(ColumnDef::new("job_token_kid").text())
                    .col(ColumnDef::new("input_ref").text())
                    .col(ColumnDef::new("output_ref").text())
                    .col(ColumnDef::new("cpu_fuel_used").big_integer())
                    .col(ColumnDef::new("wall_time_ms").big_integer())
                    .col(ColumnDef::new("peak_memory_bytes").big_integer())
                    .col(ColumnDef::new("output_bytes").big_integer())
                    .col(ColumnDef::new("invocation_count").integer())
                    .col(
                        ColumnDef::new("http_request")
                            .boolean()
                            .not_null()
                            .default(Expr::cust("false")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table("usage_rollups")
                    .col(ColumnDef::new("tenant_id").text().not_null())
                    .col(ColumnDef::new("period_start").date().not_null())
                    .col(ColumnDef::new("component_id").text().not_null())
                    .col(
                        ColumnDef::new("invocation_count")
                            .big_integer()
                            .not_null()
                            .default(Expr::cust("0")),
                    )
                    .col(
                        ColumnDef::new("cpu_fuel_used")
                            .big_integer()
                            .not_null()
                            .default(Expr::cust("0")),
                    )
                    .col(
                        ColumnDef::new("wall_time_ms")
                            .big_integer()
                            .not_null()
                            .default(Expr::cust("0")),
                    )
                    .col(
                        ColumnDef::new("peak_memory_bytes_max")
                            .big_integer()
                            .not_null()
                            .default(Expr::cust("0")),
                    )
                    .col(
                        ColumnDef::new("output_bytes")
                            .big_integer()
                            .not_null()
                            .default(Expr::cust("0")),
                    )
                    .col(
                        ColumnDef::new("succeeded_count")
                            .big_integer()
                            .not_null()
                            .default(Expr::cust("0")),
                    )
                    .col(
                        ColumnDef::new("failed_count")
                            .big_integer()
                            .not_null()
                            .default(Expr::cust("0")),
                    )
                    .col(
                        ColumnDef::new("timeout_count")
                            .big_integer()
                            .not_null()
                            .default(Expr::cust("0")),
                    )
                    .col(
                        ColumnDef::new("updated_at")
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .primary_key(
                        Index::create()
                            .col("tenant_id")
                            .col("period_start")
                            .col("component_id"),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table("function_secrets")
                    .col(ColumnDef::new("id").text().not_null().primary_key())
                    .col(ColumnDef::new("tenant_id").text().not_null())
                    .col(ColumnDef::new("component_id").text().not_null())
                    .col(ColumnDef::new("name").text().not_null())
                    .col(ColumnDef::new("current_version").integer().not_null())
                    .col(
                        ColumnDef::new("created_at")
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .col(
                        ColumnDef::new("updated_at")
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .col(ColumnDef::new("deleted_at").timestamp_with_time_zone())
                    .col(
                        ColumnDef::new("deploy_allowed")
                            .boolean()
                            .not_null()
                            .default(Expr::cust("false")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table("function_secret_versions")
                    .check(Expr::col("reason").is_in(["create", "rotate", "rekey"]))
                    .col(ColumnDef::new("tenant_id").text().not_null())
                    .col(ColumnDef::new("secret_id").text().not_null())
                    .col(ColumnDef::new("version").integer().not_null())
                    .col(ColumnDef::new("kek_kid").text().not_null())
                    .col(ColumnDef::new("wrapped_dek").binary().not_null())
                    .col(ColumnDef::new("dek_nonce").binary().not_null())
                    .col(ColumnDef::new("nonce").binary().not_null())
                    .col(ColumnDef::new("ciphertext").binary().not_null())
                    .col(ColumnDef::new("value_len").integer().not_null())
                    .col(ColumnDef::new("reason").text().not_null())
                    .col(
                        ColumnDef::new("created_at")
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .col(ColumnDef::new("created_by").text())
                    .primary_key(
                        Index::create()
                            .col("tenant_id")
                            .col("secret_id")
                            .col("version"),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table("component_signing_keys")
                    .check(Expr::col("status").is_in(["active", "retired"]))
                    .col(ColumnDef::new("tenant_id").text().not_null())
                    .col(ColumnDef::new("key_id").text().not_null())
                    .col(ColumnDef::new("public_key").text().not_null())
                    .col(
                        ColumnDef::new("status")
                            .text()
                            .not_null()
                            .default(Expr::cust("'active'::text")),
                    )
                    .col(
                        ColumnDef::new("created_at")
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .col(ColumnDef::new("created_by").text())
                    .primary_key(Index::create().col("tenant_id").col("key_id"))
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table("version_configs")
                    .col(ColumnDef::new("tenant_id").text().not_null())
                    .col(ColumnDef::new("component_id").text().not_null())
                    .col(ColumnDef::new("version_id").text().not_null())
                    .col(ColumnDef::new("key").text().not_null())
                    .col(ColumnDef::new("value").text().not_null())
                    .col(
                        ColumnDef::new("updated_at")
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .primary_key(
                        Index::create()
                            .col("tenant_id")
                            .col("version_id")
                            .col("key"),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table("version_secret_bindings")
                    .col(ColumnDef::new("tenant_id").text().not_null())
                    .col(ColumnDef::new("component_id").text().not_null())
                    .col(ColumnDef::new("version_id").text().not_null())
                    .col(ColumnDef::new("secret_id").text().not_null())
                    .col(ColumnDef::new("name").text().not_null())
                    .primary_key(
                        Index::create()
                            .col("tenant_id")
                            .col("version_id")
                            .col("name"),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table("artifact_reservations")
                    .col(ColumnDef::new("id").text().not_null().primary_key())
                    .col(ColumnDef::new("tenant_id").text().not_null())
                    .col(ColumnDef::new("version_id").text().not_null())
                    .col(ColumnDef::new("storage_uri").text().not_null())
                    .col(ColumnDef::new("wasm_sha256").text().not_null())
                    .col(
                        ColumnDef::new("expires_at")
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("(now() + '00:05:00'::interval)")),
                    )
                    .col(
                        ColumnDef::new("cleanup_retry_at")
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table("platform_maintenance")
                    .check(Expr::col("singleton").eq(true))
                    .col(
                        ColumnDef::new("singleton")
                            .boolean()
                            .not_null()
                            .primary_key()
                            .default(Expr::cust("true")),
                    )
                    .col(ColumnDef::new("owner").text())
                    .to_owned(),
            )
            .await?;
        super::m20260915_000001_indexes::create(manager).await?;
        manager
            .get_connection()
            .execute_unprepared(include_str!("m20260915_000001_security.sql"))
            .await?;
        Ok(())
    }

    async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        Err(DbErr::Custom("The baseline cannot be rolled back in place; recreate a disposable database explicitly.".into()))
    }
}
