apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hibana
resources:
  - ../../migration
images:
  - name: registry.example.com/hibana/platform
    newName: hibana-platform
    newTag: dev
