apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hibana
resources:
  - ../base
  - access.yaml
images:
  - name: registry.example.com/hibana/platform
    newName: hibana-platform
    newTag: dev
patches:
  - target:
      kind: Service
      name: hibana-api
    patch: |-
      - op: add
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30080
  - target:
      kind: Service
      name: hibana-apps
    patch: |-
      - op: add
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30083
  - target:
      kind: ConfigMap
      name: hibana-config
    patch: |-
      - op: replace
        path: /data/S3_ENDPOINT
        value: "http://hibana-minio:9000"
      - op: replace
        path: /data/INGRESS_BASE_DOMAIN
        value: "hibana.local"
  - target:
      kind: Namespace
      name: hibana
    patch: |-
      - op: replace
        path: /metadata/labels/pod-security.kubernetes.io~1enforce
        value: baseline
