apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - console.yaml
  - ingress.yaml
images:
  - name: hibana-console
    newName: registry.example.com/hibana/console
    newTag: replace-with-release
